services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - orderprocessing-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Taitueg903?
    ports:
      - "1433:1433"
    networks:
      - orderprocessing-network

  order-service:
    build:
      context: .
      dockerfile: OrderService/OrderService.API/Dockerfile
    container_name: order-service
    depends_on:
      - rabbitmq
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5103:5103"
      - "5203:5203"
    networks:
      - orderprocessing-network

  product-service:
    build:
      context: .
      dockerfile: ProductService/ProductService.API/Dockerfile
    container_name: product-service
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5041:5041"
      - "5241:5241"
    networks:
      - orderprocessing-network

  payment-service:
    build:
      context: .
      dockerfile: PaymentService/PaymentService.API/Dockerfile
    container_name: payment-service
    depends_on:
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
      - RabbitMQ__Username=${RABBITMQ_DEFAULT_USER}
      - RabbitMQ__Password=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5104:5104"
    networks:
      - orderprocessing-network

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    container_name: api-gateway
    depends_on:
      - order-service
      - product-service
      - payment-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    networks:
      - orderprocessing-network

networks:
  orderprocessing-network:
    driver: bridge
